"""Constants for Rheem EcoNet."""

DOMAIN = "rheem_econet"
NAME = "Rheem EcoNet Tankless"
MANUFACTURER = "Rheem"
MODEL = "RTGH-RH11DVLN"
PRODUCT_NUMBER = "689371"
CONTROLLER_REVISION = "00.06"
DEFAULT_SOURCE_ADDRESS = 0x340
DEFAULT_DESTINATION_ADDRESS = 0x1040
BAUD_RATE = 38400
UPDATE_INTERVAL = 5
MIN_TEMPERATURE = 110.0
MAX_TEMPERATURE = 140.0

DP_TEMP_IN = "TEMP__IN"
DP_TEMP_OUT = "TEMP_OUT"
DP_BTUS = "WTR_BTUS"
DP_WATER_USED = "WTR_USED"
DP_FLOW_RATE = "FLOWRATE"
DP_IGNITION_CYCLES = "IGNCYCLS"
DP_SETPOINT = "WHTRSETP"
DP_ENABLE = "WHTRENAB"

READ_DATAPOINTS = (
    DP_TEMP_IN,
    DP_TEMP_OUT,
    DP_BTUS,
    DP_WATER_USED,
    DP_FLOW_RATE,
    DP_IGNITION_CYCLES,
    DP_SETPOINT,
    DP_ENABLE,
)
